services:
  typescript-app:
    build:
      context: .
      args:
        NEXT_PUBLIC_SUPABASE_URL: ${NEXT_PUBLIC_SUPABASE_URL}
        NEXT_PUBLIC_SUPABASE_ANON_KEY: ${NEXT_PUBLIC_SUPABASE_ANON_KEY}
        NEXT_PUBLIC_FIREBASE_API_KEY: ${NEXT_PUBLIC_FIREBASE_API_KEY}
        NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: ${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}
        NEXT_PUBLIC_FIREBASE_PROJECT_ID: ${NEXT_PUBLIC_FIREBASE_PROJECT_ID}
        NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: ${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}
        NEXT_PUBLIC_FIREBASE_MESSAGING_sender_id: ${NEXT_PUBLIC_FIREBASE_MESSAGING_sender_id}
        NEXT_PUBLIC_FIREBASE_APP_ID: ${NEXT_PUBLIC_FIREBASE_APP_ID}
        NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID: ${NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID}
        NEXT_PUBLIC_FIREBASE_VAPID_KEY: ${NEXT_PUBLIC_FIREBASE_VAPID_KEY}
    container_name: typescript-app
    restart: unless-stopped
    init: true
    ports:
      - "3000:3000" # Expose Next.js app on port 3000
    env_file:
      - ./.env
      - ./.env.local
    # If you add a database or other services, add 'depends_on' here
    # networks: [default]  # Uncomment if you add more services/networks

    # No external services (e.g., database, cache) detected in documentation or codebase.
    # If you add a database (e.g., PostgreSQL for Supabase), add it here and configure networking and persistence accordingly.

    # No volumes section included, as there are no persistent data requirements for this service.
